### ISSUE TITLE
Link to expost version

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#17]
On padm.us you can prepend "expost." to any pad to get a markdown rendering of it.

I see there's a plugin to add a toolbar button that links to a static URL:

https://www.npmjs.com/package/ep_button_link

Could we adapt that to link to "http://expost.padm.us/foo" where foo is the current pad?

**Comment by skalinchuk** [comment]
Sorry, I don't quite understand what you mean under "markdown". I see markdown plugin (https://www.npmjs.com/package/ep_markdown) that allows editing and exporting markdown, but it adds the formatting options, that we kind of trying to remove :-)

If this plugin does what you expect, we can definitely add markdown rendering. I can add a button and add a route line new.padm.us/expost/{pad_id}

**Comment by dreeves** [comment]
This is something different. Check out expost.padm.us -- short version is that if there's plaintext markdown at padm.us/foo then expost.padm.us/foo will magically display it all nicely formatted.

We never do formatting in the etherpad itself.

So the button to add is to expost.padm.us/{pad_id}

**Comment by dreeves** [comment]
PS: Here's the repo for Expost: https://github.com/bsoule/expost

But no need to worry about Expost for now. It's hosted as its own thing.

The action item for this Issue is to just make a button to the left of the import/export button that does a target=_blank link to "http://expost.padm.us/foo" where "foo" is the pad_id of the pad we're on.
