### ISSUE TITLE
Default public pad?

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#18]
The landing page we have is kind of pointless. You know what would be cool? A default public pad when you surf to http://padm.us . Of course we could redirect to padm.us/public but I'd rather not give people the hint that they can try random URLs and stumble on our pads. So ideally going to the bare padm.us URL would show the /public pad, exactly the same as going to padm.us/public would.

**Comment by skalinchuk** [comment]
We can do that of course. But what if some people start posting there something "unethical" or even "illegal"? We will have to be notified of any change, otherwise we risk creating an uncontrolled environment

**Comment by dreeves** [comment]
Oh, I'm not worried about that. I've had totally public web pages where anyone could type anything for almost 20 years now. In fact, anyone with unmoderated comments on a blog has the same risk. I think it's understood that you just do your best to clean up after vandals but you're not liable for anything they do even though you've technically facilitated it.

In any case, I like the idea of getting notifications of changes. I think there's a plugin to make that easy. But let's make that a separate issue. I'm ok with a default public pad at http://padm.us

**Comment by dreeves** [comment]
Done via embedding. Thanks Sergii!
