### ISSUE TITLE
Pad change notifier

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#21]
Initial spec: Send an email to dreeves@gmail.com when a pad is created and/or updated.

I believe there's a plugin to facilitate that. Maybe this:
https://www.npmjs.com/package/ep_email_notifications

**Comment by skalinchuk** [comment]
I have found the same plugin, but it's based on subscription (no ability for create notification) - I think we will have to develop that one by ourselves. Although, as soon as there is a module for sending emails from NodeJS environment (which definitely exists), it's very easy to make a message sending plugin.

**Comment by dreeves** [comment]
I have a node app that sends me mail when someone updates something: https://gomix.com/#!/project/caitlin

But let's snooze this for now since it's not high enough priority to write our own plugin at this point.
