### ISSUE TITLE
Pad-listing script

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#23]
On Etherpad 1.1 I had a command-line script like so for listing all the pads:

```
# padlist.sh lists all the pads
mysql -u USERNAME -pPASSWORD etherpad_lite -e 'select store.key from store' | grep -Eo '^pad:[^:]+' | sed -e 's/pad://' | sort | uniq -c | sort -rn | awk '{if ($1!="2") {print $2 }}' 
```

I need something like that for a script I use to keep local backups on my laptop of all pads.

**Comment by skalinchuk** [comment]
I wonder why it worked, because the name of the database is actually etherpad, not etherpad_lite. Maybe I was looking at incorrect DB instance?

**Comment by dreeves** [comment]
Mystery resolved! etherpad_lite is the correct database!

So probably this same script is going to continue to work. Can you put a version of it with the right username/password on the new server and let me know the path to it?

**Comment by dreeves** [comment]
This works now! Is there a good place in the repo to check that script in? I also have a more elaborate one that runs on my laptop and calls out to padlist.sh on the server. I'm not sure whether stuff like that would be better in a separate repository or what...
