### ISSUE TITLE
Migrate to new server

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#24]
Tentative plan:

1. edit nginx to stop serving from padm.us and pad.beeminder.com and other aliases people might be using. ie downtime begins (can't have people editing pads during migration)
2. do the migration by copying from old.padm.us to new.padm.us (how long does this take?)
3. edit zonefile to point padm.us at the new server, same as new.padm.us (dns TTL is 5 minutes so should be quick)
4. old site remains available at old.padm.us until we're confident the new site is solid

**Comment by skalinchuk** [comment]
Migration by copying content via php-extension takes 50 minutes. As for other variants, I am not sure.
