### ISSUE TITLE
Remove most formatting buttons

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#4]
The only one we want is strikethrough. That's actually sometimes useful when proposing stuff to delete when working on a shared document. For the other ones (italics, bold, underline, bulleted lists) I actually don't want them because we confuse ourselves when editing markdown. Like people italicize something in the source and then we lose it when we interpret it as markdown.

**Comment by skalinchuk** [comment]
Completed by editing settings.json

**Comment by dreeves** [comment]
(Customizable in settings)
