### ISSUE TITLE
Private pads?

### ISSUE THREAD

**Issue by dreeves** [dreeves/etherpad#9]
I want to default to totally public pads (as long as Google doesn't index them) but it would occasionally be nice to lock a pad down with a password or something.

This is low priority, definitely after we've migrated the old pads.

**Comment by skalinchuk** [comment]
There definitely is such an option already, I just need to figure out how to switch it on.

**Comment by dreeves** [comment]
If this is easy it might be worth trying before we migrate, in case it breaks things.

**Comment by dreeves** [comment]
Looks like this isn't part of Etherpad currently. Closing.
